version: 2

models:
  - name: transformed_pizzas
    description: DBT Transformed layer, all clumn upper case and date and time column added
    columns:
      - name: size
        description: The size of the pizza
        tests:
        - not_null
      - name: price
        description: The price of the pizza
        tests:
        - not_null
      - name: pizza_id
        description: Unique Identifier - Pizza type ID (distinguish Size)
        tests:
        - unique
        - not_null
      - name: fk_pizza_type_id
        description: General Pizza ID (does not distinguish Size)
        tests:
        - not_null
        - relationships:
            to: ref('transformed_pizza_types')
            field: pizza_type_id
      - name: dbt_DateCreated
        description: date record created
        tests:
        - not_null
      - name: dbt_TimeCreated
        description: Time record created
        tests:
        - not_null

  - name: transformed_pizza_types
    description: DBT Transformed layer, all clumn upper case and date and time column added
    columns:
      - name: name
        description: The name of the pizza type
        tests:
        - not_null
      - name: category
        description: The category of the pizza type
        tests:
        - not_null
      - name: ingredients
        description: The ingredients of the pizza type
        tests:
        - not_null
      - name: pizza_type_id
        description: PK - General Pizza ID (does not distinguish Size)
        tests:
        - unique
        - not_null
      - name: dbt_DateCreated
        description: date record created
      - name: dbt_TimeCreated
        description: Time record created
